name: counter_app
description: An example app showing basic usage of Framy.
version: 1.0.0+1


environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  framy_annotation:
    git:
      url: https://github.com/Baljefry/framy.git
      ref: master #branch name
      path: framy_annotation  #Folder Path on Github


dev_dependencies:
  build_runner: any
  framy_generator:
    path: ../

flutter:
  uses-material-design: true

#dependency_overrides:
#  framy_annotation:
#    path: ../../framy_annotation
