name: framy_generator
description: A convenient code generator for app styleguide, gallery, storyboard and more.
version: 0.3.3
repository: https://github.com/Fidev-io/framy
homepage: https://framy.dev

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  glob: ^2.1.2
  analyzer: ^6.4.1  #https://github.com/flutter/flutter/issues/56779
  meta: ^1.10.0
  framy_annotation:
    git:
      url: https://github.com/Baljefry/framy.git
      ref: master #branch name
      path: framy_annotation  #Folder Path on Github

  yaml: ^3.1.2
  pedantic: ^1.9.2

dev_dependencies:
  build_runner: ^2.4.8
  test: ^1.25.2
  mockito: ^5.4.4
  source_gen_test: ^1.0.6

#dependency_overrides:
#  framy_annotation:
#    path: ../framy_annotation

analyzer:
  enable-experiment:
    - non-nullable
